version: '3'
services:
  web:
    image: openseed-osm-website:v1
    build:
      context: ./openstreetmap-website
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file: 
      - ./.env
    depends_on:
      - db
  db:
    image: openseed-db:v1
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file: 
      - ./.env
  replication:
    image: openseed-replication:v1
    build: 
      context: ./osmosis
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    command: >
      /bin/bash -c "
      echo Sleep the replication for a while!;
      sleep 40;
      echo Creating the replication!;
      ./start.sh"
    env_file:
      - ./.env
  db-backup-restore:
    image: openseed-db-backup-restore:v1
    build: 
      context: ./db-backup-restore
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    command: >
      /bin/bash -c "
      echo Sleep for a while!;
      sleep 20;
      echo Building backup!;
      ./start.sh"
    env_file: 
      - ./.env
  gl-tiles-server:
    image: gl-tiles-server:v1
    build: 
      context: ./gl-tiles-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - web
      - db
    command: >
      /bin/bash -c "
      echo Sleep for a while!;
      sleep 20;
      echo Building backup!;
      ./start.sh"
    env_file: 
      - ./.env