version: '3'
services:
  web:
    image: openseed-osm-website:v1
    build:
      context: ./openstreetmap-website
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file: 
      - ./.env
    depends_on:
      - db
    networks: 
      - web_network
      - db_network
  db:
    image: openseed-db:v1
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file: 
      - ./.env
    networks: 
      - db_network
  replication:
    image: openseed-replication:v1
    build: 
      context: ./osmosis
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    command: >
      /bin/bash -c "
      echo Sleep the replication for a while!;
      sleep 40;
      echo Creating the replication!;
      ./start.sh"
    env_file: 
      - ./.env
  db-backup-restore:
    image: openseed-db-backup-restore:v1
    build: 
      context: ./db-backup-restore
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    command: >
      /bin/bash -c "
      echo Sleep for a while!;
      sleep 20;
      echo Building backup!;
      ./start.sh"
    env_file: 
      - ./.env
  id:
    image: openseed-id-editor:v1
    build: 
      context: ./iD
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - web
      - db
    env_file: 
      - ./.env
    networks: 
      - web_network
  nginx: 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
     - ./nginx/nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
    command: >
      /bin/bash -c "
      envsubst '$${SERVER_PORT} $${SERVER_URL}' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf 
      && nginx -g 'daemon off;'"
    env_file: 
      - ./.env
    environment:
      - SERVER_URL
      - SERVER_PORT
    ports:
      - "80:80"
    networks: 
      - web_network
      - db_network
    depends_on: 
      - web
      - db
      - id
networks: 
  web_network: 
    driver: bridge
  db_network: 
    driver: bridge