apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "osm-seed.fullname" . }}-id-editor
  labels:
    app: {{ template "osm-seed.name" . }}
    component: id-editor-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.idEditor.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-id-editor
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-id-editor
    spec:
      containers:
        - name: {{ .Chart.Name }}-id-editor
          image: "{{ .Values.idEditor.image }}:{{ .Values.osmSeedVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: OAUTH_CONSUMER_KEY
              value: {{ .Values.idEditor.env.OAUTH_CONSUMER_KEY }}
            - name: OAUTH_SECRET
              value: {{ .Values.idEditor.env.OAUTH_SECRET }}
            - name: SERVER_URL
              value: {{ .Values.idEditor.env.OSM_API_DOMAIN }}
            - name: SERVER_PROTOCOL
              value : {{ .Values.idEditor.env.OSM_API_PROTOCOL }}